ad_server:
  build: ./docker/ad_server
  links:
    - mysql
nginx:
  build: ./docker/nginx/
  links:
    - ad_server
  volumes_from:
    - ad_server
  env_file: ./docker/env_file

mysql:
  image: mysql:5.6
  env_file: ./docker/env_file